modelname: clip_late-fusion
basemodel: clip
_target_: src.model.clip.clip_cir_late_fusion.clip_cir_late_fusion

model:
  _target_: src.model.clip.clip_cir_late_fusion.CLIPCirLateFusion
  temperature: 0.07
  embed_dim: 768
  hidden_dim: 512
  loss: ${model.loss}
  ckpt_path: ${model.ckpt.path}

  train_vit: False
  vit: "large"
